### PR TITLE
Added the ability to return the message ID instead of boolean on ->send() (Take 2)

### PR DESCRIPTION
**Pull request by beauwest**
Here's the second iteration. Let me know what you think.

### CODE REVIEW

**Comment by beauwest** [comment]
I decided to make it an option off of send, just to make absolutely sure it doesn't break anyone's code. If they're looking for 

```
->send === true 
```

It would break.

**Comment by Znarkus** [comment]
Good, I like it!

Would you mind changing `public function send($returnId = false)` to something like `public function send($options = array())`? That could then be used like this: `->send(array('returnMessageId' => true))`, which is more readable imo.

**Comment by beauwest** [comment]
Done.

**Comment by Znarkus** [comment]
Thanks! Out of curiosity, why do you use `!empty(` instead of `!isset(`?

**Comment by beauwest** [comment]
In case they set it to false manually. Empty catches false or blank, or not set.

**Comment by Znarkus** [comment]
Thanks!

**Pull request merged**
