### PR TITLE
Added the ability to build a URL directly to the Postmark page

### PR DESCRIPTION
**Pull request by beauwest**
This can be used to store in the database so the administrators of your site can directly link to the Postmark email.

An alternative option, if you don't want to hard-code the URL would be to just return the message ID from the send() function. The app can then build it's own URL.

### CODE REVIEW

**Comment by Znarkus** [comment]
Hi,

Good suggestion. But to keep this class as simple as possible, I'd prefer to just add a method "getLastMessageId" or something.

Also, why did you change the coding standard?

Markus

**Comment by beauwest** [comment]
It sounded like a good idea at the time, hehe.

If I get time I'll go ahead and break out the method and just include a getLastMessageId. Feel free to do it if you want to as well! Do you want it to be a separate method? Or do you just want ->send() to return it?

**Comment by beauwest** [comment]
Right now ->send() returns either debug info or true. If an error occurs it throws an Exception. So returning a string shouldn't break anyone's logic if they're doing something like:

```
if($mail->send()) {}
```

**Comment by Znarkus** [comment]
Okay. Otherwise I could just add this to the next milestone, and I will incorporate it with the other changes. And of course credit you. Don't when that will come though

**Comment by beauwest** [comment]
Withdrawing this pull request, will switch to old formatting and make the changes.

**Pull request closed without merging**
