### PR TITLE
Made PSR-0 compliant, added support for Composer and removed constants

### PR DESCRIPTION
**Pull request by gabrielbull**

### CODE REVIEW

**Comment by Znarkus** [comment]
Looks great, please see the comment above.

**Comment by gabrielbull** [comment]
Composer requires an email address.

**Comment by Znarkus** [comment]
Can't find anything about that in the [specs](http://getcomposer.org/doc/04-schema.md#authors), are you sure?

**Comment by gabrielbull** [comment]
Yes, I tried without emails and it throws an error.

**Comment by Znarkus** [comment]
Alright. Merging. Thanks!

**Pull request merged**
