### PR TITLE
international support: encode non-utf8 strings for compatibility with json_encode

### PR DESCRIPTION
**Pull request by solkennedy**
A fix for:

Error Message:
json_encode(): Invalid UTF-8 sequence in argument

Where:
postmark.php, line 326

Since json_encode does not support non-utf8 strings (example: ถ.พิทักษ์), it was throwing this error when trying to send email containing non-utf8 strings. This fix utf8 encodes the strings before passing them to json_encode.

### CODE REVIEW

**Comment by Znarkus** [comment]
I'm not sure that I understand the issue. What does `_utf8_fix()` do?

**Comment by solkennedy** [comment]
If you have a non-utf character (like บณต), this breaks json_encode, so utf8_fix converts those characters to utf8 first.  

## 

Bryan Kennedy
aboutbryan.com
415.413.4112

**Comment by Znarkus** [comment]
Why not just encode it to utf8 prior to sending it to Postmark? Postmark only works with utf8 as far as I know, as does this lib. Try using [`utf8_encode()`](http://php.net/utf8_encode) instead.

I realize that it doesn't state this requirement in the docs, I will fix this. Sorry about that.

**Comment by solkennedy** [comment]
Whatever you think is best. This solution solved our problem, so I figured it might be helpful. I'm sorry it was not. 

## 

Bryan Kennedy
aboutbryan.com
415.413.4112

**Comment by Znarkus** [comment]
Thank you for trying to help, sorry for not accepting it.

**Pull request closed without merging**
